### ISSUE TITLE
Example does not work

### ISSUE THREAD

**Issue by bsqrl** [adafruit/Adafruit_Python_LSM303#1]
Running the example, I get an error:

Traceback (most recent call last):
  File "simpletest.py", line 21, in <module>
    accel, mag = lsm303.read()
  File "build/bdist.linux-armv6l/egg/Adafruit_LSM303/LSM303.py", line 80, in read
struct.error: unpack requires a string argument of length 6

**Comment by tdicola** [comment]
Hrm it sounds like something might be up with the I2C connection or power to the sensor and you're not getting back the expected number of bytes.  Check the wiring (make sure it isn't super long for example), and make sure the sensor has the right power & ground.  If the sense doesn't send any data back from the read command like you see then it sounds like it might not be powered.  I can't repro the issue with my sensor though so I'll close this for now, thanks and good luck!
