### ISSUE TITLE
LSM303.set_mag_gain does not refer instantiated object

### ISSUE THREAD

**Issue by ggoetz** [adafruit/Adafruit_Python_LSM303#5]
LSM303.set_mag_gain does not refer instantiated object. 

Consequently, the following code fails: 
`lsm303 = Adafruit_LSM303.LSM303()`
`lsm303.set_mag_gain(gain=0x80)`
with a TypeError: set_mag_gain() got multiple values for argument 'gain'

Changing line 88 of LSM303.py from:
`def set_mag_gain(gain=LSM303_MAGGAIN_1_3):`
to
`def set_mag_gain(self, gain=LSM303_MAGGAIN_1_3):`
fixes the issue.

**Comment by ggoetz** [comment]
Pull request #3 fixes the issue.

**Comment by siddacious** [comment]
Thank you.

This library has been replaced by two new libraries, one for each sensor in the LSM303DLH:

https://github.com/adafruit/Adafruit_CircuitPython_LSM303_Accel
https://github.com/adafruit/Adafruit_CircuitPython_LSM303DLH_Mag

Your specific feedback isn't relevant to the new library but thank you for taking the time to point it out.
