### ISSUE TITLE
typo in commented example code

### ISSUE THREAD

**Issue by gchristian321** [adafruit/Adafruit_Python_LSM303#6]
Hello, I found a small typo in the example code `examples/simpletest.py`.

In the "alternative" (commented) instantiation of the `lsm303` object with a specified bus (line 16), the argument

```busum=2```

should be

```busnum=2```

**Comment by siddacious** [comment]
Thank you.

This library has been replaced by two new libraries, one for each sensor in the LSM303DLH:

https://github.com/adafruit/Adafruit_CircuitPython_LSM303_Accel
https://github.com/adafruit/Adafruit_CircuitPython_LSM303DLH_Mag

Your specific feedback isn't relevant to the new library but thank you for taking the time to point it out.
